language: php

php:
   - 5.3
   - 5.4
   - 5.5
   - 5.6
   - hhvm

services:
   - memcached

env:
   - PECL_MEMCACHED=memcached-1.0.2
   - PECL_MEMCACHED=memcached-2.0.1
   - PECL_MEMCACHED=memcached-2.1.0
   - PECL_MEMCACHED=memcached-2.2.0

before_script:
   - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then yes "" | pecl install -f "$PECL_MEMCACHED"; fi;'
   # Need to activate memchached extension explictly to work with all versions.
   - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-add .travis-php.ini; fi;'
   - composer self-update || true
   # Ensure the memcached extension is available
   - composer show --platform ext-memcached
   - composer install --no-interaction

script:
   - vendor/bin/phpunit -c phpunit.xml.dist --coverage-text
